//
const SUCCESS = 200;
//
const SERVER_ERROR = 500;
//
const INVALID_PARAMETER = 422;
const INVALID = 400;
const UNAUTHOTIZED = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;

const NEW_RESOURCE_CREATED = 201;

const RESOURCE_DELETED = 204;

const ALREADY_EXIST = 409;
const WENT_WRONG =501;
const SOMETHING_WENT_WRONG = 503;


export {
    SERVER_ERROR,
    INVALID_PARAMETER,
    INVALID,
    UNAUTHOTIZED,
    FORBIDDEN,
    SUCCESS,
    NOT_FOUND,
    NEW_RESOURCE_CREATED,
    RESOURCE_DELETED,
    ALREADY_EXIST,
    WENT_WRONG,
    SOMETHING_WENT_WRONG
}